os:
  - linux
  - osx
  - windows
dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
jobs:
  include:
    - stage: duckling
      name: "Duckling on Docker with tests"
      services: docker
      before_install:
        - docker pull rasa/duckling
        - docker run -d -p 0.0.0.0:8000:8000 rasa/duckling
install: 
  # all three OSes agree about 'pip3'
  - pip3 install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .  
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 setup.py test || python setup.py test
