dist: xenial # required for Python >= 3.7
language: python
matrix:
  include:
    - stage: test
      name: "Test 3.6"
      python: "3.6"
      services: docker
      before_install:
        - docker pull rasa/duckling
        - docker run -d -p 0.0.0.0:8000:8000 rasa/duckling
    - name: "Test 3.7"
      python: "3.7"
      services: docker
      before_install:
        - docker pull rasa/duckling
        - docker run -d -p 0.0.0.0:8000:8000 rasa/duckling
install:
  - pip install -r requirements.txt
  - python setup.py install
script: python3 setup.py test || python setup.py test
after_success:
  - coveralls