dist: xenial # required for Python >= 3.7
language: python
matrix:
  include:
    - stage: test
      name: "Test 3.6"
      python: "3.6"
      services: docker
      before_install:
        - docker pull rasa/duckling
        - docker run -d -p 0.0.0.0:8000:8000 rasa/duckling
      install:
        - pip install -r requirements.txt
        - python setup.py install
      script: python3 setup.py test || python setup.py test
    - name: "Test 3.7"
      python: "3.7"
      services: docker
      before_install:
        - docker pull rasa/duckling
        - docker run -d -p 0.0.0.0:8000:8000 rasa/duckling
      install:
        - pip install -r requirements.txt
        - python setup.py install
      script: python3 setup.py test || python setup.py test
    - stage: deploy
      install: true
      script: skip
      deploy:
        provider: pypi
        user: "Nicolas_Drbs"
        password:
          secure: "Hyar5MNU7HFCP7EBLarmM0RdaONZP/MzjT1zjSc0g2iVRhtDMsWMOp9CnRHHyleeDH/+3ZyabJLQ5m7hRDMf/iC5ADgQx0+yNdS/p6b3v+hZC0vkD25xTIN6AkJT0vCl3C+Hi3kzLT19//D+NIeD5cIYumA7/4P2oaJvB0bajqZGswgLvHdLvG8bt3bzL/G78peJFGkDv7uumBT2BKiPrc02QvzMlp1WFpoFZIjayxDmLDDH2ipc5aQvRR30rc0G9TlGFH9YMReVoBr0UofDOVmSbdyPHcB3WcIAnQYaOCBe3N4ZXxlIW1aGr6kAsmtNWCJ0MK9sTCNikMEf4bV3BRgBxjeY4WDJ9RQlt4LeTYHFcU7AE97Wq76wsJSxzzPhasuRts3jukUpnEyKjZMapaPmk8/HfcP8LFxVnmelYKZAko1HFKnEgDBIlc+8CsOrolculiE17Dn29pBONLHMwNZMmn3tRSKWZcZnqrPRReTYm7ejdmaea2ejfHa0Zqbg7upWxyCoqRw3GlctAz2w4/EDcPgWJ5k97vHFlktTgXImB1vm4BPkhPIfqkzgDWz2nwxnDPV8R8Fms98WnCT0oT1wQuxaW1FtVRFhhaioRCeg0p0yxudSm03f48TK7LiYrx/6dS1vt0mxc3x0Nz4NNyIL5d96zEkWxODomVJ0l38="

stages:
  - test
  - deploy

after_success:
  - coveralls
